### ISSUE TITLE
KDL wrapper depends on angles library which is ROS1 package

### ISSUE THREAD

**Issue by bhomaidan1990** [yumi-crew/yumi#1]
Hi, I use ROS2 **Foxy** on Ubuntu `20.04`, and I have got the following error message while following the installation instruction:
`colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

> The ERROR: 
```
--- stderr: kdl_wrapper                                                                                                           
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findangles.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "angles", but
  CMake did not find one.

  Could not find a package configuration file provided by "angles" with any
  of the following names:

    anglesConfig.cmake
    angles-config.cmake

  Add the installation prefix of "angles" to CMAKE_PREFIX_PATH or set
  "angles_DIR" to a directory containing one of the above files.  If "angles"
  provides a separate development package or SDK, be sure it has been
  installed.


---
Failed   <<< kdl_wrapper [3.83s, exited with code 1]

```
Is there a way to solve this problem with [angles](https://github.com/ros/angles) which seems to be a `Catkin` package? thanks in advance.

**Comment by avgprog** [comment]
I had a similar error. I solved it by building and installing code in the [ros2 branch of the same repo](https://github.com/ros/angles/tree/ros2).
